<div class="col-md-10">        
    <h2 class="panel_heading_style"><img src="<?php  echo base_url(); ?>/assets/images/trainee.png"> Trainee - Bulk Registration</h2>        
    <div class="table-responsive">
        <?php
        if($error) echo '<font color="red">'.$error.'</font>';
         echo validation_errors('<div class="error">', '</div>'); 
        if ($this->session->flashdata('success')) {
            echo '<div class="success">' .$this->session->flashdata('success'). '</div>';
        }
        if ($this->session->flashdata('error_message')) {
            echo '<div class="error1">' . $this->session->flashdata('error_message') . '</div>';
        }
        ?>
        <?php $form_attributes = array('name' => 'bulk_registration', 'id' => 'bulk_registration', "onsubmit" => "return(validate());");
        echo form_open_multipart("trainee/bulk_registration", $form_attributes);
        ?>
        <table class="table table-striped">
          <tbody>
            <tr>
              <td width="20%" class="td_heading">Import Trainee Detail:<span class="required">*</span></td>
              <td colspan="2" width="25%">
                  <input name="userfile" type="file" id="xls_file" onchange="validate_trainee_bulk(this)" > 
                  <span id="xls_file_err"></span>
              </td>
              <td width="18%" ><button type="submit" name="upload" id="upload" value="upload" class="btn btn-xs btn-primary no-mar"><span class="glyphicon glyphicon-upload"></span> Upload</button> <span style="font-weight:bold;">(xls or xlsx)</span></td>
              <td colspan="3" width="20%">
              <span class="pull-right"><a href="<?php echo base_url().'trainee/download_xls';?>" class="small_text1">
              <span class="label label-default black-btn"><span class="glyphicon glyphicon-download-alt"></span> Download Import XLS</span></a></span> 
              </td>
            </tr>
          </tbody>
        </table>
        <?php echo form_close(); ?>      
    </div>   
    <div class="table-responsive">
        <table class="table table-striped">
        <tr>
		<?php if($files && $trainee_data){ ?>
            <td width="20%">
                           
                <span class="pull-right"><a href="<?php echo base_url()."trainee/download_import_xls/".$files;?>" class="small_text1">
              <span class="label label-default black-btn"><span class="glyphicon glyphicon-export"></span> Export to XLS</span></a></span> 
            </td>
		<?php } ?>
        </tr>
        </table>
   </div>            
    <h2 class="sub_panel_heading_style"><span class="glyphicon glyphicon-zoom-in"></span> Import Preview </h2>
    <div class="excel">
    <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>NRIC/FIN No.</th>
              <th>Account Type</th>
              <th>Company Name</th>
              <th>User Name</th>
              <th>Password</th>
              <th>Name</th>              
              <th>Import Status</th>
              <th>Failure Reason</th>
            </tr>
          </thead>
        <tbody>
          <?php         
          foreach($trainee_data as $k=>$data){       
        ?>
             <?php if($k != 'flag'){?>  <!--added by shubhranshu-->
              <tr>
                <td><?php 
                if(empty($data['taxcode'])){
                    echo $data['userid'];
                    
                }else{
                    echo $data['taxcode'];} ;?> 
                </td>
                <td> <?php echo ($data['CompanyCode'])?'Company':'Individual';?></td>
                <td> <?php echo ($data['CompanyName'])?$data['CompanyName'].'('.$data['CompanyCode'].')':$data['CompanyCode'];?></td>
                <td> <?php echo $data['username'];?></td>
                <td> <?php echo $data['password'];?></td>
                <td> <?php echo $data['firstname'];?></td>                
                <td> <?php if($data['rowstatus'] == 'fail') echo '<font color="red" > Failed. </font>'; else echo '<font color="green"> Success. </font>';?></td>
                <td> <?php if($data['rowstatus'] == 'fail') echo $data['failure_reason']; ?></td>
              </tr>
          <?php  } }?>
        </tbody>
        </table>
        </div>
    </div>          
          
    <div style="clear:both;"></div><br>
          <span class="required required_i"><i>(Password will be auto-generated by the application and the accounts will be activated by-passing the requirement for activation by email.)</i><br><br></span>
          <span class="required required_i">* Required Fields</span>
    </div>
    
<!---------- /*  added by shubhranshu for client requirement on 21/03/2019 */-->
<div class="modal1_055" id="ex22" <?php if($trainee_data['flag']==false) {echo "style='display:none'";}?>>         
    <h2 class="panel_heading_style">Warning</h2>   
    <div  style="margin-top:7%">
        <p style="text-align: center;" >
            The trainees whom you are about to register is part of the restricted list. Please acknowledge to continue !!!
        </p>
        <div class="popup_cancel9">
            <span rel="modal:close">
                <a href="#" rel="modal:close"><button class="btn btn-primary trainee_deatils_yes" type="button">Yes, I understand.</button></a>
            </span>
            
        </div>
    </div>
</div>

<!--//////////////////////////////////////////////////////-->
<script>
function validate() {
    var result = validate_trainee_bulk();
    if(result == false){
        return false;
    }else {
        check_nric_restriction();
        return true;
    }
}    
function check_nric_restriction(){
    $.ajax({
            url: "check_nric_restriction",
            type: "post",
            dataType: "json",
            data: {tax_code: $nric},
            success: function(res) {
                if (res == 1) {
                    $('#ex111').modal();
                } 
            }
    });
}
</script>


<!--//-->
<script>
    $(document).ready(function(){
        $role_id = "<?php echo $this->session->userdata('userDetails')->role_id;?>";///added by shubhranshu
        $privilage = "<?php echo $privilage;?>";///added by shubhranshu
        var flag = "<?php echo $trainee_data['flag'];?>";
        if($privilage == '0'){///added by shubhranshu
            if($role_id == 'ADMN'){///added by shubhranshu
                 if(flag == 'true'){$('#ex22').modal();}  ///added by shubhranshu
            }///added by shubhranshu
        }else if($privilage == '1'){
            if(flag == 'true'){$('#ex22').modal();}///added by shubhranshu
        }
    });
    
</script>
<!---------- /*  added by shubhranshu for client requirement on 21/03/2019 */-->